### ISSUE TITLE
Recursive process.nextTick in bigpipe?

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#10]
I came back to my computer and found this. I would have opened it on `bigpipe/bigpipe` but the log is from this app.

https://gist.github.com/indexzero/a02d3951997923e3c8cc

**Comment by 3rd-Eden** [comment]
I've been trying to track this down in bigpipe but nothing in bigpipe it self is using `process.nextTick`. So it has to be caused by the submodules but it's really unfortunate that node doesn't provide a stack trace for this "error".

It would be nice if this was reproducible some how so I could create a custom node build with a `console.trace()` for that statement.

@Swaagie have you ever seen this happening before?

**Comment by 3rd-Eden** [comment]
@indexzero when you came back to you computer, was it sleep mode? As I do remember that I got some `process.nextTick`'s in Primus.. So it could be that reconnect or something like is causing this.

**Comment by Swaagie** [comment]
Haven't seen this happening before, my first suspect would be primus as well

**Comment by Swaagie** [comment]
potential offensive code https://github.com/mattpat/node-schedule/blob/master/lib/schedule.js#L501, checking several things now to see if this triggers a recursive loop

**Comment by Swaagie** [comment]
Checked 3 things, no failures, although suspending the machine did create some awkward output.

https://gist.github.com/Swaagie/1cd26871682be537a727
- drop internet connection while running
- set the time to 23:59:00 just before starting
- suspend the machine while browsenpm.org was running --> to much ping output on the same time interval just before or while suspended, but didn't hit recursive nextTick.

**Comment by Swaagie** [comment]
I think I know what happens, but it is hard to reproduce, basically combine the 2nd and 3rd tick above. Node-schedule will add alot of jobs if the time is incremented (basically for each interval that has passed since). That alongside with suspending the machine and the observed effect could enhance the number of jobs and registered callbacks to the size where max callstack is hit.

**Comment by Swaagie** [comment]
Pretty sure this only happens when a machine is put in standby/sleep, have seen it happening for arnout as well. And even then the recursive maxTick is a false positive for the amount of functions that get queued at the same time
