### ISSUE TITLE
HTML template rendering issue

### ISSUE THREAD

**Issue by mybecks** [nodejitsu/browsenpm.org#25]
Hello,

if I search for the package [grunt](http://browsenpm.org/package/grunt) or some grunt-contrib-\* packages an error is displayed

`
Failed to render: package, /root/browsenpm/node_modules/packages-pagelet/view.ejs:181 179| <tr class="<%= index >= 5 ? 'gone' : '' %>"> 180| <td 
class="version"><%= version %></td> >> 181| <td class="date" data-date="<%= 
package.time[version].full %>"> 182| <%= package.time[version].ago %> 183| </td> 184| 
<td class="releaser right"> Cannot read property 'full' of undefined
`
BR,
mybecks

**Comment by 3rd-Eden** [comment]
I found the problem here. In the npm data structure there's a time object which contains the release time of every package you publish to npm. But for some odd reason there are releases missing for grunt. My theory is that these versions are "pre-release" and are only tagged by npm and not seen as an actual release because they are missing a lot of meta data.

Long story short, never trust npm's data structure to be complete \o. Fix will pushed live in a couple of minutes. Thanks for taking the time to report this issue!

See https://github.com/nodejitsu/packages-pagelet/commit/8be467179e0d9f13a986472e5c81c9eaf3151070 for the actual fix.
